packages:
  - 'packages/gstate_wasm'
  - 'packages/gstate_wasm_test'
  - 'packages/cards_ts'
  - 'packages/onnx_test'
  - 'packages/inferencer_test'
link-workspace-packages: true
prefer-workspace-packages: true
